class CreateYfhCityGroups < ActiveRecord::Migration
  def self.up
    add_column :groups, :location, :boolean
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Adana', 'Projenin etki ettiği yer Adana', 'approved', lower('Adana'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Adiyaman', 'Projenin etki ettiği yer Adiyaman', 'approved', lower('Adiyaman'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Afyon', 'Projenin etki ettiği yer Afyon', 'approved', lower('Afyon'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Ağri', 'Projenin etki ettiği yer Ağri', 'approved', lower('Ağri'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Aksaray', 'Projenin etki ettiği yer Aksaray', 'approved', lower('Aksaray'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Amasya', 'Projenin etki ettiği yer Amasya', 'approved', lower('Amasya'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Ankara', 'Projenin etki ettiği yer Ankara', 'approved', lower('Ankara'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Antalya', 'Projenin etki ettiği yer Antalya', 'approved', lower('Antalya'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Ardahan', 'Projenin etki ettiği yer Ardahan', 'approved', lower('Ardahan'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Artvin', 'Projenin etki ettiği yer Artvin', 'approved', lower('Artvin'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Aydin', 'Projenin etki ettiği yer Aydin', 'approved', lower('Aydin'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Balikesir', 'Projenin etki ettiği yer Balikesir', 'approved', lower('Balikesir'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Bartin', 'Projenin etki ettiği yer Bartin', 'approved', lower('Bartin'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Batman', 'Projenin etki ettiği yer Batman', 'approved', lower('Batman'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Bayburt', 'Projenin etki ettiği yer Bayburt', 'approved', lower('Bayburt'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Bilecik', 'Projenin etki ettiği yer Bilecik', 'approved', lower('Bilecik'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Bingöl', 'Projenin etki ettiği yer Bingöl', 'approved', lower('Bingöl'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Bitlis', 'Projenin etki ettiği yer Bitlis', 'approved', lower('Bitlis'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Bolu', 'Projenin etki ettiği yer Bolu', 'approved', lower('Bolu'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Burdur', 'Projenin etki ettiği yer Burdur', 'approved', lower('Burdur'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Bursa', 'Projenin etki ettiği yer Bursa', 'approved', lower('Bursa'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Çanakkale', 'Projenin etki ettiği yer Çanakkale', 'approved', lower('Çanakkale'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Çankiri', 'Projenin etki ettiği yer Çankiri', 'approved', lower('Çankiri'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Çorum', 'Projenin etki ettiği yer Çorum', 'approved', lower('Çorum'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Denizli  ', 'Projenin etki ettiği yer Denizli  ', 'approved', lower('Denizli  '), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Diyarbakir', 'Projenin etki ettiği yer Diyarbakir', 'approved', lower('Diyarbakir'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Düzce', 'Projenin etki ettiği yer Düzce', 'approved', lower('Düzce'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Edirne', 'Projenin etki ettiği yer Edirne', 'approved', lower('Edirne'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Elaziğ', 'Projenin etki ettiği yer Elaziğ', 'approved', lower('Elaziğ'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Erzincan', 'Projenin etki ettiği yer Erzincan', 'approved', lower('Erzincan'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Erzurum', 'Projenin etki ettiği yer Erzurum', 'approved', lower('Erzurum'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Eskişehir', 'Projenin etki ettiği yer Eskişehir', 'approved', lower('Eskişehir'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Gaziantep', 'Projenin etki ettiği yer Gaziantep', 'approved', lower('Gaziantep'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Giresun', 'Projenin etki ettiği yer Giresun', 'approved', lower('Giresun'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Gümüşhane', 'Projenin etki ettiği yer Gümüşhane', 'approved', lower('Gümüşhane'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Hakkari', 'Projenin etki ettiği yer Hakkari', 'approved', lower('Hakkari'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Hatay', 'Projenin etki ettiği yer Hatay', 'approved', lower('Hatay'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Iğdir', 'Projenin etki ettiği yer Iğdir', 'approved', lower('Iğdir'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Isparta', 'Projenin etki ettiği yer Isparta', 'approved', lower('Isparta'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Istanbul', 'Projenin etki ettiği yer Istanbul', 'approved', lower('Istanbul'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Izmir', 'Projenin etki ettiği yer Izmir', 'approved', lower('Izmir'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Kahramanmaraş', 'Projenin etki ettiği yer Kahramanmaraş', 'approved', lower('Kahramanmaraş'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Karabük', 'Projenin etki ettiği yer Karabük', 'approved', lower('Karabük'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Karaman', 'Projenin etki ettiği yer Karaman', 'approved', lower('Karaman'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Kars', 'Projenin etki ettiği yer Kars', 'approved', lower('Kars'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Kastamonu', 'Projenin etki ettiği yer Kastamonu', 'approved', lower('Kastamonu'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Kayseri', 'Projenin etki ettiği yer Kayseri', 'approved', lower('Kayseri'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Kilis', 'Projenin etki ettiği yer Kilis', 'approved', lower('Kilis'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Kirikkale', 'Projenin etki ettiği yer Kirikkale', 'approved', lower('Kirikkale'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Kirklareli', 'Projenin etki ettiği yer Kirklareli', 'approved', lower('Kirklareli'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Kirşehir', 'Projenin etki ettiği yer Kirşehir', 'approved', lower('Kirşehir'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Kocaeli', 'Projenin etki ettiği yer Kocaeli', 'approved', lower('Kocaeli'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Konya', 'Projenin etki ettiği yer Konya', 'approved', lower('Konya'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Kütahya', 'Projenin etki ettiği yer Kütahya', 'approved', lower('Kütahya'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Malatya', 'Projenin etki ettiği yer Malatya', 'approved', lower('Malatya'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Manisa', 'Projenin etki ettiği yer Manisa', 'approved', lower('Manisa'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Mardin', 'Projenin etki ettiği yer Mardin', 'approved', lower('Mardin'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Mersin', 'Projenin etki ettiği yer Mersin', 'approved', lower('Mersin'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Muğla', 'Projenin etki ettiği yer Muğla', 'approved', lower('Muğla'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Muş', 'Projenin etki ettiği yer Muş', 'approved', lower('Muş'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Nevşehir', 'Projenin etki ettiği yer Nevşehir', 'approved', lower('Nevşehir'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Niğde', 'Projenin etki ettiği yer Niğde', 'approved', lower('Niğde'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Ordu', 'Projenin etki ettiği yer Ordu', 'approved', lower('Ordu'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Osmaniye', 'Projenin etki ettiği yer Osmaniye', 'approved', lower('Osmaniye'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Rize', 'Projenin etki ettiği yer Rize', 'approved', lower('Rize'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Sakarya', 'Projenin etki ettiği yer Sakarya', 'approved', lower('Sakarya'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Samsun', 'Projenin etki ettiği yer Samsun', 'approved', lower('Samsun'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Şanliurfa', 'Projenin etki ettiği yer Şanliurfa', 'approved', lower('Şanliurfa'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Siirt', 'Projenin etki ettiği yer Siirt', 'approved', lower('Siirt'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Sinop', 'Projenin etki ettiği yer Sinop', 'approved', lower('Sinop'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Şirnak', 'Projenin etki ettiği yer Şirnak', 'approved', lower('Şirnak'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Sivas', 'Projenin etki ettiği yer Sivas', 'approved', lower('Sivas'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Tekirdağ', 'Projenin etki ettiği yer Tekirdağ', 'approved', lower('Tekirdağ'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Tokat', 'Projenin etki ettiği yer Tokat', 'approved', lower('Tokat'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Trabzon', 'Projenin etki ettiği yer Trabzon', 'approved', lower('Trabzon'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Tunceli', 'Projenin etki ettiği yer Tunceli', 'approved', lower('Tunceli'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Uşak', 'Projenin etki ettiği yer Uşak', 'approved', lower('Uşak'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Van', 'Projenin etki ettiği yer Van', 'approved', lower('Van'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Yalova', 'Projenin etki ettiği yer Yalova', 'approved', lower('Yalova'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Yozgat', 'Projenin etki ettiği yer Yozgat', 'approved', lower('Yozgat'), now(), now());"
    execute "insert into groups (location, creator_id, name, description, state, url_key, created_at, updated_at) values (true, 2, 'Zonguldak', 'Projenin etki ettiği yer Zonguldak', 'approved', lower('Zonguldak'), now(), now());"
  end

  def self.down
    remove_column :groups, :location
  end
end


